### ISSUE TITLE
Is there anyway to customise the snaps?

### ISSUE THREAD

**Issue by x9sim9** [velitasali/gnome-shell-extension-awesome-tiles#11]
Hi with portrait screens I sometimes want to divide the screen into more than 3 windows vertically but I have to do this manually, is there a way to change the snap sizes. I would benefit from 1/4 and 1/6 screen height options, thanks, simon

**Comment by velitasali** [comment]
Hi. It is not currently possible, and since this extension aims to have a simple workflow, I am not sure how we can implement it  doing something completely different. That said, I am open to new ideas. If you come up with a simple workflow for what you described above (like someone did for successive key pressed here https://github.com/velitasali/gnome-shell-extension-awesome-tiles/discussions/2), I can implement it.
