### ISSUE TITLE
Shortcut combos of 3 keys not detected properly

### ISSUE THREAD

**Issue by howels** [velitasali/gnome-shell-extension-awesome-tiles#12]
When using super+Left for tile-left and super+shift+left for tile-upper-left this cannot distinguish between the two key combinations and only traps the super+left portion, ignoring the modifier. Other tiling plugins correctly handle this.

**Comment by howels** [comment]
Seems I have to hammer the 3-key shortcuts incredibly fast to capture them. Suggest that the capturing of existing shortcuts should be disabled when the config window is open too? Otherwise it's necessary to un-map a 2-key shortcut before mapping a 3-key modified version of that shortcut, then re-map the 2-key variant afterwards..

**Comment by velitasali** [comment]
When I unset the key combinations in question from GNOME Shell in the system settings, I am able to use them with this extension. Have you tried that?
![Screenshot from 2022-04-23 14-57-56](https://user-images.githubusercontent.com/10258162/164893546-e5ac5119-126f-461a-a213-50fe97ba5c0b.png)

**Comment by howels** [comment]
> When I unset the key combinations in question from GNOME Shell in the system settings, I am able to use them with this extension. Have you tried that? ![Screenshot from 2022-04-23 14-57-56](https://user-images.githubusercontent.com/10258162/164893546-e5ac5119-126f-461a-a213-50fe97ba5c0b.png)

I had already unset the combinations in system settings (I was replacing an older tiling manager with this), the problem was trying to assign 3-key shortcuts as they were not properly detected. For instance when using Super+Left to tile left but also using Super+Shift+Left to tile in Top-Left quarter.

**Comment by velitasali** [comment]
Hi again! I will need you to double-check because I am unable to reproduce this issue. After I remove the bindings from the system settings, I am able to use those two combinations. 

**System settings:**

![Screenshot from 2022-06-18 18-43-18](https://user-images.githubusercontent.com/10258162/174446050-5b51c223-021c-45ce-8a0a-f2741c1ec033.png)

**Extension settings:**

![Screenshot from 2022-06-18 18-42-45](https://user-images.githubusercontent.com/10258162/174446075-1ef25172-8217-4808-a4f6-c3935ee0be95.png)

**Comment by velitasali** [comment]
Hi, I am closing this due to lack of response. Feel free to reopen it.

**Comment by howels** [comment]
I have stopped using gnome shell, so I can't test.
