### ISSUE TITLE
Aspect ratio option

### ISSUE THREAD

**Issue by eboye** [velitasali/gnome-shell-extension-awesome-tiles#3]
Hi,

great extension. I really love the simplicity of it! I was actually looking for an extension that would allow me to make the tiles split custom and found yours that is truly simple so I can modify it :)

Here's my changes: https://github.com/eboye/gnome-shell-extension-awesome-tiles/commits/main

As I'm really really new to gnome shell extensions, I'm pretty bad at making those options. But if you could make some kind of presets for tile splitting and incorporate that into the tile function.

I'm using a 21:9 monitor ultra wide and I often need to split my screen to 16:9 + 5:9. More often then anything else.

Also, I'm not sure if it's possible, but it would be great if there was an option to set preset per screen :) As I have another 16:9 screen that would be great if had regular tiling. But this one is less of an important to me :)

Anyhow, thanks a bunch for making this extension.

**Comment by velitasali** [comment]
Hi,

I can see an improvement here, but 16:9 + 5:9 seems to be a very opinionated scale, so I will need to find a way to incorporate it without making things too complicated. We are already discussing 3-grid tiling as a possibility (here https://github.com/velitasali/gnome-shell-extension-awesome-tiles/discussions/2), so 2+1 rather than 16:9 + 5:9 looks sounds easier to achieve, although 16:9 is also a reasonable scale. 

Another thing I am wondering is if the gaps are a problem here because they are calculated separately for the height and width, so left and right gaps in theory should be larger in your case. 

Btw, I am glad the extension is useful :)

**Comment by eboye** [comment]
I know it's very very opinionated. 2+1 would suffice :)

I just thought of some dropdown option for few "most used" and/or input number field for aspect.

And yes, I noticed that gap is trublesome, but it's 0 in my case, so I don't have issues :)

**Comment by velitasali** [comment]
We are testing 3/2 and 3/1 tiling with successive key presses. Could you give it a go?

To see the effect, press `<Super>Keypad 4` a second time for instance. The changes are on this branch https://github.com/velitasali/gnome-shell-extension-awesome-tiles/tree/successive-tiling

Also, it would be nice if you could give feedback on the gap size. I haven't changed anything related to it yet, but I might put a limit to how long it stretches.

**Comment by eboye** [comment]
I like it! It's even better than my thingy :)

As for the gaps, well I'm not going to use them, but I must say that X axis gap is much bigger that Y axis one and looks a bit strange. I think it should not be percentage based but fixed amount.

**Comment by velitasali** [comment]
Ok, I am going to move my changes to main then. 

I will also do something about the gaps :)

**Comment by eboye** [comment]
Hmm, after and update, I think one before the last, when I tile the window to 2/3 and then click on in or any window of that app it goes back to 1/2.

**Comment by velitasali** [comment]
@eboye That is an upstream bug. You can track the issue https://github.com/velitasali/gnome-shell-extension-awesome-tiles/issues/9 for that.
